# Generated by Django 5.0.4 on 2024-06-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tivs_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
