# Generated by Django 5.0.4 on 2024-07-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tivs_app', '0002_rename_user_id_appuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income', models.FloatField()),
                ('name_email_similarity', models.FloatField()),
                ('prev_address_months_count', models.IntegerField()),
                ('current_address_months_count', models.IntegerField()),
                ('customer_age', models.IntegerField()),
                ('days_since_request', models.FloatField()),
                ('intended_balcon_amount', models.FloatField()),
                ('payment_type', models.CharField(max_length=255)),
                ('zip_count_4w', models.IntegerField()),
                ('velocity_6h', models.FloatField()),
                ('velocity_24h', models.FloatField()),
                ('velocity_4w', models.FloatField()),
                ('bank_branch_count_8w', models.IntegerField()),
                ('date_of_birth_distinct_emails_4w', models.IntegerField()),
                ('employment_status', models.CharField(max_length=255)),
                ('credit_risk_score', models.IntegerField()),
                ('email_is_free', models.IntegerField()),
                ('housing_status', models.CharField(max_length=255)),
                ('phone_home_valid', models.IntegerField()),
                ('phone_mobile_valid', models.IntegerField()),
                ('bank_months_count', models.IntegerField()),
                ('has_other_cards', models.IntegerField()),
                ('proposed_credit_limit', models.FloatField()),
                ('foreign_request', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('session_length_in_minutes', models.FloatField()),
                ('device_os', models.CharField(max_length=255)),
                ('keep_alive_session', models.IntegerField()),
                ('device_distinct_emails_8w', models.IntegerField()),
                ('device_fraud_count', models.IntegerField()),
                ('month', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
