# Generated by Django 5.0.4 on 2024-07-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tivs_app', '0003_blacklistmodel_customerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistmodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
