# Generated by Django 5.0.4 on 2024-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tivs_app', '0004_alter_blacklistmodel_phone_alter_customerdata_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('error', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
