# Generated by Django 5.0.4 on 2024-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tivs_app', '0006_blacklistmodel_user_customerdata_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='verified',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
