# Generated by Django 5.0.4 on 2024-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tivs_app', '0007_customerdata_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='failed_reason',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
