# Generated by Django 5.0.4 on 2024-07-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tivs_app', '0008_customerdata_failed_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdata',
            old_name='failed_reason',
            new_name='reason',
        ),
    ]
