# Generated by Django 5.0.4 on 2024-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tivs_app', '0011_rename_task_name_errorlogsmodel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogsmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlogsmodel',
            name='date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlogsmodel',
            name='laundering_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlogsmodel',
            name='payment_currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlogsmodel',
            name='received_currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlogsmodel',
            name='receiver_account',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlogsmodel',
            name='receiver_bank_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlogsmodel',
            name='sender_account',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlogsmodel',
            name='sender_bank_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlogsmodel',
            name='time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='laundering_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='payment_currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='received_currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='receiver_account',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='receiver_bank_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='sender_account',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='sender_bank_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedcustomerdata',
            name='time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='laundering_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='payment_currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='received_currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='receiver_account',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='receiver_bank_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='sender_account',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='sender_bank_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passedcustomerdata',
            name='time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='laundering_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='payment_currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='received_currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='receiver_account',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='receiver_bank_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='sender_account',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='sender_bank_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repassedcustomerdata',
            name='time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errorlogsmodel',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='failedcustomerdata',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passedcustomerdata',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='repassedcustomerdata',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
    ]
