version: '3.8'

services:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: my_db
  #     POSTGRES_USER: my_user
  #     POSTGRES_PASSWORD: my_password
  #   ports:
  #     - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"