# render.yaml

services:
  - type: web
    name: my-site-web
    env_file: .env
    build:
      context: https://github.com/Transaction-Verification-System/web--backend.git # Update with your repo URL
      dockerfile: Dockerfile
    start_command: uvicorn my_site.asgi:application --host 0.0.0.0 --port 8000
    env_file: .env


  - type: worker
    name: my-site-celery-worker
    env_file: .env
    build:
      context: https://github.com/Transaction-Verification-System/web--backend.git # Update with your repo URL
      dockerfile: Dockerfile
    start_command: celery -A my_site worker -Q queue_1,queue_2 -l info

  - type: scheduler
    name: my-site-celery-beat
    env_file: .env
    build:
      context: https://github.com/Transaction-Verification-System/web--backend.git # Update with your repo URL
      dockerfile: Dockerfile
    start_command: celery -A my_site beat -l info

